### ISSUE TITLE
OSS Gate Workshop: Online: 2020-10-31: knokmki612: oss-gate/issue-cleaner: Work log

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#1428]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by knokmki612** [comment]
https://github.com/oss-gate/issue-cleaner リポジトリはここ
ライセンスはISC

**Comment by knokmki612** [comment]
now.sh v1が終了して動作が止まっているので、GitHub Actionsに移行したい

**Comment by knokmki612** [comment]
> GitHub Actionsに移行したい

そのものずばりのissueが今立っていないので、issueの整理からやるべき？

**Comment by knokmki612** [comment]
関連のissue
https://github.com/oss-gate/issue-cleaner/issues/15
https://github.com/oss-gate/issue-cleaner/issues/11
https://github.com/oss-gate/issue-cleaner/issues/7

**Comment by knokmki612** [comment]
上記3件と、probot、now関係のissueの計6件を閉じた

**Comment by knokmki612** [comment]
GitHub Actions関係の利用経験がないので、ドキュメントを読みながらアクションの作成をする
https://docs.github.com/ja/free-pro-team@latest/actions/creating-actions/about-actions

**Comment by knokmki612** [comment]
GitHub Actionsを動かして試すのにこれを使ってみようかなと思っている
https://github.com/nektos/act

**Comment by knokmki612** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions#types-of-actions

> You can build Docker container and JavaScript actions. 

Dockerコンテナを動かして何かをするだけだと思っていたんだけど、JavaScriptでもタスクというかアクションが書けるのか…

**Comment by knokmki612** [comment]
ドキュメントが英語でも日本語でも用意されているので、ざっと読み進めるのに日本語で読んでおいて、大事そうなところは英語でも読んでおこうかと思った

**Comment by knokmki612** [comment]
action.yml
https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions

JavaScriptのアクションの作成
https://docs.github.com/ja/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action

あたりを読んでいる

**Comment by knokmki612** [comment]
何も考えずチュートリアル通り作ってみる https://github.com/knokmki612/hello-world-javascript-action

**Comment by knokmki612** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#testing-out-your-action-in-a-workflow
> When an action is in a private repository, the action can only be used in workflows in the same repository.

actionを作ったリポジトリで、自分自身をインストールすることも可能なのか

**Comment by knokmki612** [comment]
```yaml
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
```

usesにリポジトリを指定するか、ローカルのaction.ymlがあるディレクトリを指定するのね
