### ISSUE TITLE
OSS Gate Workshop: TOKYO: 2017-07-29: kakimoto: -: Work log

### ISSUE THREAD

**Issue by cuon-kakimoto** [oss-gate/workshop#513]
```yaml
type: supporter
questions:
  # 参加した理由
  motivation:
    # どうしてこのワークショップに参加しようと思いましたか？
    # どうしてOSSの開発に参加したいと思っていますか？
    # みんなのためとか世界のためとかでもよいですが、
    # 個人的な理由でもまったく問題ありません。
    # 自分の思っていることを大事にしたいのです。
    # アイスブレイクのときに話した内容でもよいですし、
    # そのあとに気持ちが変わったらなら変わった気持ちでよいです。
    |
    （回答）
    前回OSSGateに参加しましたが、その後OSSの開発に参加することがなかったので、
    今回もう一度参加してリベンジしました。
  # 見つけた場所
  via:
    # どこでこのワークショップを知りましたか？
    |
    （回答）
    毎回、開催メールが飛んできていましたので。
  # このワークショップでビギナーをサポートできましたか？
  supported:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- 非常にサポートできた
    - サポートできた
    #- サポートできなかった
    #- まったくサポートできなかった
  # 満足度
  satisfaction-rating:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- すごく満足した
    - 満足した
    #- 不満だった
    #- すごく不満だった
  # 想定との違い
  difference:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    - 想定より充実していた
    #- 想定通りだった
    #- 期待はずれだった
    #- すごく期待はずれだった
  # 「動かす」作業の時間配分について
  run-time:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- 長かった
    - ちょうどよかった
    #- 短かった
  # 「フィードバック」作業の時間配分について
  feedback-time:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- 長かった
    - ちょうどよかった
    #- 短かった
  # 進行役について
  moderator:
    # 進行役はうまく進行できていましたか？
    # 進行役の説明はどうでしたか？
    # スライドの内容を理解するのに役立ちましたか？
    |
    （回答）
    良かったです。ユーザ視点でのOSS開発で良いということがわからいました。
  # サポートメンターについて
  support-mentor:
    # サポートメンターはサポーターがいないときの代役としてうまくフォローできていましたか？
    # サポートメンターはサポーターをうまくフォローできていましたか？
    |
    （回答）
    必要なときにフォローを受けれましたので、良かったです。
  # 進行役のやりやすさについて
  moderator-likely:
    # 自分が進行役をやることを考えたときに、
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- 自分一人でもなんとかやれそう
    - サポートする人がいれば自分でもやれそう
    #- サポートする人がいても自分ではやれなさそう
  # 次回のOSS Gateワークショップについて
  next:
    # ↓のうち当てはまるものをすべて選んでコメントを外してください。
    #- ビギナーとして参加する
    - サポーターとして参加する
    #- 進行役として参加する
    #- まわりの人にOSS Gateワークショップを紹介する
    #- まわりの人と一緒にOSS Gateワークショップに参加する
  # その他
  etc:
    # なにか思ったことがあれば自由に書いてください。
    |
    （回答）
    ビギナーとして申込みをしたが、人数の関係のためサポーターとして対応をした。
    ユーザ視点でのOSS開発だったので、自分の知識を伝えるではなく、OSSの開発の始め方を伝えて、一緒に考えることができてサポートできた。
    ビギナーの方がiseueを立てて、PRを送るまで達成することが出来たので、満足しました。
    サポーターとして勉強になり、新人育成に役立てていければと思います。

```
