### ISSUE TITLE
アンケートyaml kinugasa

### ISSUE THREAD

**Issue by KimiakiKinugasa** [oss-gate/workshop#514]
```yaml
type: beginner
questions:
  # 参加した理由
  motivation:
    # どうしてこのワークショップに参加しようと思いましたか？
    # どうしてOSSの開発に参加したいと思っていますか？
    # みんなのためとか世界のためとかでもよいですが、
    # 個人的な理由でもまったく問題ありません。
    # 自分の思っていることを大事にしたいのです。
    # アイスブレイクのときに話した内容でもよいですし、
    # そのあとに気持ちが変わったらなら変わった気持ちでよいです。
    |
    （回答）
    OSS開発してる人は技術力が高そうでなんか格好いいと思うので
    そんなエンジニアになれたらいいなと思って、このワークショップに参加しました。
  # 見つけた場所
  via:
    # どこでこのワークショップを知りましたか？
    |
    （回答）
    OSS開発したい みたいなワードでググったらこのワークショップを見つけました。
  # 開発対象
  target:
    # ワークショップで開発対象に選んだOSSはなんですか？
    |
    （回答）
    cygwin
  # 満足度
  satisfaction-rating:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- すごく満足した
    - 満足した
    #- 不満だった
    #- すごく不満だった
  # 想定との違い
  difference:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- 想定より充実していた
    - 想定通りだった
    #- 期待はずれだった
    #- すごく期待はずれだった
  # 「動かす」作業の時間配分について
  run-time:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- 長かった
    #- ちょうどよかった
    - 短かった
  # 「フィードバック」作業の時間配分について
  feedback-time:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- 長かった
    - ちょうどよかった
    #- 短かった
  # 進行役について
  moderator:
    # 進行役はうまく進行できていましたか？
    # 進行役の説明はどうでしたか？
    # スライドの内容を理解するのに役立ちましたか？
    |
    （回答）
    説明はわかりやすく、スムーズに進行していたと思います。
  # サポートメンターについて
  support-mentor:
    # サポートメンターはサポーターがいないときの代役としてうまくフォローできていましたか？
    # サポートメンターはサポーターをうまくフォローできていましたか？
    |
    （回答）
    困ったときに色々と助言をもらえたので助かりました。
  # 次回のOSS Gateワークショップについて
  next:
    # ↓のうち当てはまるものをすべて選んでコメントを外してください。
    - ビギナーとして参加する
    #- サポーターとして参加する
    #- まわりの人にOSS Gateワークショップを紹介する
    #- まわりの人と一緒にOSS Gateワークショップに参加する
  # 今後のOSSの開発への参加について
  future:
    # ↓のうち当てはまるものを1つ選んでコメントを外してください。
    #- 機会を作って積極的に開発に参加するし、まわりの人が開発に参加することも手伝う
    #- 機会を作って積極的に開発に参加する
    - 機会があれば開発に参加する
    #- 機会があったら開発に参加したい（けどできなそう）
    #- 機会があっても開発に参加しない
  # その他
  etc:
    # なにか思ったことがあれば自由に書いてください。
    |
    （回答）
    自分だけではissueを上げるだけでも敷居の高さを感じてしまい、
    何もできなかったと思いますが、サポーターの後押しがあったおかげで一歩踏み出せてよかったです。
```
