### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-11-25: kaacun: elasticsearch-ruby: Work log

### ISSUE THREAD

**Issue by kaacun** [oss-gate/workshop#671]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kaacun** [comment]
elasticsearch-rubyで検索してgithubのページにたどり着いた
https://github.com/elastic/elasticsearch-ruby

**Comment by kaacun** [comment]
githubのページでライセンスを確認
Apache 2 license

**Comment by okkez** [comment]
よろしくおねがいします！

**Comment by rtusys** [comment]
よろしくおねがいします！

**Comment by kanakumagai** [comment]
よろしくお願いいたします:bow:

**Comment by kaacun** [comment]
rubyのdockerイメージを確認
https://hub.docker.com/_/ruby/

**Comment by kaacun** [comment]
elasticsearchのdockerイメージを確認
https://hub.docker.com/_/elasticsearch/

**Comment by kaacun** [comment]
docker-compose.ymlを作成
まずは素のrubyとelasticsearchを構築
```
version: '2'
services:
  web:
    image: ruby

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
```

**Comment by kaacun** [comment]
docker-compose up

**Comment by kaacun** [comment]
rubyコンテナが死んだ
ossgate_web_1 exited with code 0

**Comment by kaacun** [comment]
メンターの方と相談してENTRYPOINT tail -f /dev/nullを指定

```
FROM ruby

ENTRYPOINT tail -f /dev/null
```

**Comment by kaacun** [comment]
```
version: '2'
services:
  web:
    build:
      context: ruby

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200
```

**Comment by kaacun** [comment]
READMEのInstallationを参考にgemをインストール

```
FROM ruby

RUN gem install elasticsearch

ENTRYPOINT tail -f /dev/null
```

**Comment by kaacun** [comment]
rubyのコンテナにログイン
docker-compose exec web bash

**Comment by kaacun** [comment]
ホストをマウント
```
version: '2'
services:
  web:
    build:
      context: ruby
    volumes:
      - "~/Workspaces/src/oss-gate:/root"

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
```
